### ISSUE TITLE
Running from R

### ISSUE THREAD

**Issue by finite2** [ATOMIC-LICHESS/ATOMKRAFT#2]
Thank you for this powerful and easy to use engine. It work great within the GUI or from the command line. I'm trying to get it working properly from a batch or shell like call within windows (from R specifically). The below input works correctly if I change the engine to stockfish 7, but using ATOMKRAFT it quits early and I have no idea why it does it or how to fix it. The output is here: [test.txt](https://github.com/ATOMIC-LICHESS/ATOMKRAFT/files/120211/test.txt).

command='"C:/Users/Finite/My Real documents/chess/atomkraft/ATOMKRAFT-master/ATOMKRAFT64.exe"'
input =c('position fen rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R b KQkq - 1 1','setoption name Hash value 2048','setoption name MultiPV value 4','go depth 20','go depth 20')

f <- tempfile()
on.exit(unlink(f))
writeLines(input, f)
flag = 0L
stdout="C:/Users/Finite/My Real documents/chess/test.out"
stderr="C:/Users/Finite/My Real documents/chess/test.out"

.Internal(system(command, as.integer(flag), f, stdout, stderr))

**Comment by ddugovic** [comment]
Since it works for Stockfish, does it work for [my Stockfish fork](https://github.com/ddugovic/Stockfish)?

To get my fork to play atomic, you need to type:

> uci
> setoption name UCI_Atomic value true
> position startpos
> go infinite

**Comment by finite2** [comment]
That worked like a charm! Many thanks!
